//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmStore0906.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FarmstoreEntities : DbContext
    {
        public FarmstoreEntities()
            : base("name=FarmstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fruit> Fruits { get; set; }
    
        public virtual ObjectResult<GetFruitsOfPage_Result> GetFruitsOfPage(Nullable<int> fruitPerPage, Nullable<int> pageNumber)
        {
            var fruitPerPageParameter = fruitPerPage.HasValue ?
                new ObjectParameter("FruitPerPage", fruitPerPage) :
                new ObjectParameter("FruitPerPage", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFruitsOfPage_Result>("GetFruitsOfPage", fruitPerPageParameter, pageNumberParameter);
        }
    }
}
